WIDTH = 840
HEIGHT = 400
SCREEN_SIZE = (WIDTH, HEIGHT)
FPS = 60
SHRIFT = ['simsunextb', 'kodchiangupc', 'kokila', 'shonarbangla',
         'mangal', 'browalliaupc', 'sakkalmajalla', 'lilyupc',
         'palatinolinotype', 'moolboran', 'franklingothicmedium',
         'cordianew', 'arial', 'angsanaupc', 'jasmineupc',
         'trebuchetms', 'microsofttaile', 'utsaah', 'malgungothic',
         'simplifiedarabicfixed', 'gisha', 'microsoftjhengheitruetype',
         'microsoftjhengheiui', 'comicsansms', 'segoeuisymbol', 'vrinda',
         'freesiaupc', 'traditionalarabic', 'aparajita', 'sitka',
         'nirmalauisemilight', 'leelawadeeui', 'gadugi', 'microsoftnewtailue',
         'dokchampa', 'segoeui', 'calibri', 'miriam', 'angsananew', 'iskoolapota',
         'kartika', 'segoeuisemilight', 'vijaya', 'nirmalaui', 'mongolianbaiti',
         'microsoftyaheitruetype', 'microsoftyaheiui', 'vani', 'arialblack',
         'irisupc', 'batang', 'batangche', 'gungsuh', 'gungsuhche', 'gautami',
         'segoeuiblack', 'cambria', 'rod', 'georgia', 'verdana', 'symbol',
         'euphemia', 'raavi', 'corbel', 'shruti', 'consolas', 'segoeuisemibold',
         'simplifiedarabic', 'cambriamath', 'daunpenh', 'nyala', 'constantia',
         'yugothic', 'cordiaupc', 'khmerui', 'aharoni', 'microsoftuighur',
         'timesnewroman', 'segoescript', 'candara', 'ebrima', 'dilleniaupc',
         'msmincho', 'mspmincho', 'browallianew', 'segoeuiemoji', 'aldhabi',
         'dfkaisb', 'simhei', 'laoui', 'couriernew', 'kalinga', 'microsoftphagspa',
         'tahoma', 'eucrosiaupc', 'kaiti', 'simsun', 'nsimsun', 'meiryo',
         'meiryoui', 'sylfaen', 'tunga', 'urdutypesetting', 'webdings',
         'plantagenetcherokee', 'gabriola', 'msgothic', 'mspgothic',
         'msuigothic', 'gulim', 'gulimche', 'dotum', 'dotumche', 'lucidasans',
         'andalus', 'leelawadee', 'fangsong', 'yumin', 'david', 'miriamfixed',
         'impact', 'levenim', 'segoeprint', 'estrangeloedessa', 'leelawadeeuisemilight',
         'narkisim', 'mingliuextb', 'pmingliuextb', 'mingliuhkscsextb', 'latha',
         'microsoftsansserif', 'frankruehl', 'mingliu', 'pmingliu', 'mingliuhkscs',
         'myanmartext', 'javanesetext', 'microsofthimalaya', 'lucidaconsole',
         'arabictypesetting', 'microsoftyibaiti', 'mvboli', 'wingdings', 'extra',
         'bookantiqua', 'centurygothic', 'bookshelfsymbol7', 'msreferencesansserif',
         'msreferencespecialty', 'freestylescript', 'juiceitc', 'kristenitc',
         'lucidahandwriting', 'mistral', 'tempussansitc', 'garamond', 'monotypecorsiva',
         'bookmanoldstyle', 'algerian', 'baskervilleoldface', 'bauhaus93', 'bell',
         'berlinsansfb', 'berlinsansfbdemi', 'bernardcondensed', 'bodonipostercompressed',
         'britannic', 'broadway', 'brushscript', 'californianfb', 'centaur', 'chiller',
         'colonna', 'cooperblack', 'footlight', 'harlowsolid', 'harrington', 'hightowertext',
         'jokerman', 'kunstlerscript', 'lucidabright', 'lucidacalligraphy', 'lucidafaxregular',
         'lucidafax', 'magneto', 'maturascriptcapitals', 'modernno20', 'niagaraengraved',
         'niagarasolid', 'oldenglishtext', 'onyx', 'parchment', 'playbill', 'poorrichard',
         'ravie', 'informalroman', 'showcardgothic', 'snapitc', 'stencil', 'vinerhanditc',
         'vivaldi', 'vladimirscript', 'widelatin', 'century', 'wingdings2', 'wingdings3', 'arialms',
         ]
SHRIFT_SIZE = 25
